import 'bootstrap/dist/css/bootstrap.css'
import { Inter } from "next/font/google";
import 'swiper/css';
import 'swiper/css/effect-coverflow';
import 'swiper/css/pagination';
import "./globals.css";
import BootstrapClient from '@/components/BootstrapClient'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        {children}
        <BootstrapClient/>
        
      </body>
    </html>
  );
}
